name: Deploy to Production

on:
  push:
    branches:
      - feature/CD

jobs:
  deployment:
    environment: CSIM-Back
    runs-on: ubuntu-latest
    steps:

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Copy OpenVPN configuration file to server
        run: wget https://ydayslyon.fr/assets/YnovVPN.ovpn

      - name: connect to VPN
        run: sudo openvpn --config vpn/config.ovpn --auth-user-pass <(echo "${{ secrets.OPENVPN_USERNAME }}\n${{ secrets.OPENVPN_PASSWORD }}")

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_HOST }}
          key: SSH_PUBLIC_KEY
          script: |
            ./deploy.sh
