name: Deploy to Production

on:
  push:
    branches:
      - feature/CD

jobs:
  deployment:
    environment: CSIM-Back
    runs-on: ubuntu-latest
    steps:

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Copy OpenVPN configuration file to server
        run: wget https://ydayslyon.fr/assets/YnovVPN.ovpn

      - name: Set up OpenVPN and SSH
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.OPENVPN_USERNAME }}
          password: ${{ secrets.OPENVPN_PASSWORD }}
          script: |
            sudo apt-get update && sudo apt-get install -y openvpn
            sudo openvpn --config ./YnovVPN.ovpn
            sleep 10
            echo ${{secrets.SSH_PUBLIC_KEY}} > ~/.ssh/key
            echo ${{secrets.SSH_KNOWS_HOSTS}} > ~/.ssh/known_hosts
            ssh -i ~/.ssh/key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} ./deploy.sh
