name: Deploy to Production

on:
  push:
    branches:
      - feature/CD

jobs:
  deployment:
    environment: CSIM-Back
    runs-on: ubuntu-latest
    steps:

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn
      
      - name: install dnsutils
        run: sudo apt-get install net-tools
      
      - name: install traceroute
        run: sudo apt-get install traceroute
      
      - name: install gawk
        run: sudo apt-get install gawk

      - name: Copy OpenVPN configuration file to server
        run: wget https://ydayslyon.fr/assets/YnovVPN.ovpn

      - name: Prepare auth user pass
        run: |
          echo "${{ secrets.OPENVPN_USERNAME }}
          ${{ secrets.OPENVPN_PASSWORD }}" > authPass.txt
        
      - name: first ifconfig
        run: ifconfig -a

      - name: connect to VPN
        run: sudo openvpn --config ./YnovVPN.ovpn --auth-user-pass authPass.txt --log "vpn.log" --daemon
      
      - name: sleep 5
        run: sleep 5
      
      - name: cat vpnlog
        run: sudo cat vpn.log
        
      - name: second ifconfig
        run: ifconfig -a

      - name: remove auth user pass
        run: rm authPass.txt

      - name: create certificate
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./deploy_key_rsa

      - name: Install ssh
        run: |
          sudo apt-get -yqq install openssh-client
          
  
      - name: Allow Ping to 10.1.1.16
        run: sudo iptables -A INPUT -p icmp --icmp-type 8 -s 10.1.1.16 -j ACCEPT
      
      - name: change main interface
        run: sudo route add default tun0
      
      - name: get tun0 ip
        run: tun0_ip=$(ifconfig tun0 | awk '/inet /{print $2}')
      
      - name: print private_ssh_key
        run: |
          mkdir ~/.ssh/
          sudo echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key_rsa

      - name: Connect to ssh
        run: ssh -o BindAddress=$tun0_ip -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
