name: Deploy to Production

on:
  push:
    branches:
      - feature/CD

jobs:
  deployment:
    environment: CSIM-Back
    runs-on: ubuntu-latest
    steps:

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Install OpenVPN
        run: sudo apt-get -yqq install ssh

      - name: Copy OpenVPN configuration file to server
        run: wget https://ydayslyon.fr/assets/YnovVPN.ovpn

      - name: Prepare auth user pass
        run: |
          echo "${{ secrets.OPENVPN_USERNAME }}
          ${{ secrets.OPENVPN_PASSWORD }}" > authPass.txt

      - name: connect to VPN
        run: sudo openvpn --config ./YnovVPN.ovpn --auth-user-pass authPass.txt --daemon

      - name: remove auth user pass
        run: rm authPass.txt

      - name: remove ynov vpn file
        run: rm ./YnovVPN.ovpn

      - name: install ssh
        run: sudo apt-get install ssh -y

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: ssh-keyscan -H SSH_HOST
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run script on remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -s' < deploy.sh
