name: Deploy to Production

on:
  push:
    branches:
      - feature/CD

jobs:
  deployment:
    environment: CSIM-Back
    runs-on: ubuntu-latest
    steps:

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Copy OpenVPN configuration file to server
        run: wget https://ydayslyon.fr/assets/YnovVPN.ovpn

      - name: Prepare auth user pass
        run: |
          echo "${{ secrets.OPENVPN_USERNAME }}
          ${{ secrets.OPENVPN_PASSWORD }}" > authPass.txt

      - name: connect to VPN
        run: sudo openvpn --config ./YnovVPN.ovpn --auth-user-pass authPass.txt --log "vpn.log" --daemon
      
      - name: sleep 5
        run: sleep 5
      
      - name: cat vpnlog
        run: sudo cat vpn.log

      - name: remove auth user pass
        run: rm authPass.txt

      - name: remove ynov vpn file
        run: rm ./YnovVPN.ovpn

      - name: create certificate
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./deploy_key_rsa

      - name: Install ssh
        run: sudo apt-get -yqq install ssh

      - name: Install ssh-pass
        run: sudo apt-get install sshpass
  
      - name: Allow Ping to 10.1.1.16
        run: sudo ufw allow from 10.1.1.16 to any proto icmp
      
      - name: ping host
        run: ping 10.1.1.16

      - name: Connect to ssh
        run: sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@10.1.1.16
