name: Deploy to Production

on:
  push:
    branches:
      - feature/CD

jobs:
  deployment:
    environment: CSIM-Back
    runs-on: ubuntu-latest
    steps:

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Copy OpenVPN configuration file to server
        run: wget https://ydayslyon.fr/assets/YnovVPN.ovpn

      - name: Prepare auth user pass
        run: |
          echo "${{ secrets.OPENVPN_USERNAME }}
          ${{ secrets.OPENVPN_PASSWORD }}" > authPass.txt

      - name: connect to VPN
        run: sudo openvpn --config ./YnovVPN.ovpn --auth-user-pass authPass.txt

      - name: Wait 5 seconds
        run: sleep 5

      - name: remove auth user pass
        run: rm authPass.txt

      - name: remove ynov vpn file
        run: rm ./YnovVPN.ovpn

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            ./deploy.sh
