name: ESLint Check

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts

      - name: ESLint check
        run: pnpm lint

      - name: Check if any errors
        id: eslint-status
        run: echo ::set-output name=has_errors::$(git diff --name-only origin/main | grep '\.jsx\?$' | xargs eslint --max-warnings=0 --format=compact || true)

      - name: Fail if there are errors
        run: |
          if [ "${{ steps.eslint-status.outputs.has_errors }}" != "" ]; then
            echo "ESLint check failed"
            exit 1
          fi
